resources:
  - name: version
    type: version
    versionTemplate:
      versionName: "0.0.1"

jobs:
  - name: release
    type: release
    steps:
      - IN: version

  - name: sample-runSh
    type: runSh
    steps:
      - TASK:
          script:
            - ls

language: none
